name: builds standalone binaries
on: 
  push:
    tags:
      - '*'
jobs:

    linux-x64:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: builds linux-x64 binary and uploads to github
          run: | 
            cd build && chmod +x build.sh 
            ./build.sh -t -p -r linux-x64
            ./build.sh -t -p -r win-x64
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
